---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-prod
  namespace: prod-2
spec:
  targetNamespace: prod-2
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: hello-world-prod
  path: ./prod
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-dev
  namespace: dev-2
spec:
  targetNamespace: dev-2
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: hello-world-dev
  path: ./dev
  prune: true
  wait: true
  timeout: 5m0s
